---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/doctors":
    get:
      summary: list doctors
      tags:
        - Doctors
    post:
      summary: Create Doctor
      tags:
        - Doctors
      responses:
        "401":
          description: invalid request
        "200":
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
                lastname:
                  type: integer
                  required: true
                speciality:
                  type: string
                  required: true
                image:
                  type: string
                  required: true
                experience:
                  type: integer
                  required: true
                consultation:
                  type: decimal
                  required: true
              required:
                - name
                - lastname
                - speciality
                - image
                - experience
                - consultation
  "/api/v1/doctors/{id}":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: show doctor
      tags:
        - Doctors
      responses:
        "401":
          description: invalid request
        "200":
          description: successful
    delete:
      summary: Delete Doctor
      tags:
        - Doctors
      responses:
        "401":
          description: invalid request
        "200":
          description: successful
  "/api/v1/appointments":
    post:
      summary: Create Appointments
      tags:
        - Appointments
      responses:
        "401":
          description: invalid request
        "200":
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  required: true
                doctor_id:
                  type: integer
                  required: true
                city:
                  type: string
                  required: true
                datetime:
                  type: string
                  format: datetime
                  required: true
              required:
                - user_id
                - doctor_id
                - city
                - datetime
    get:
      summary: List of appointments
      tags:
        - Appointments
  "/api/v1/appointments/{id}":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    delete:
      summary: Delete Appointments
      tags:
        - Appointments
      responses:
        "401":
          description: authentication failed
        "200":
          description: successful
  "/login":
    post:
      summary: Log in
      tags:
        - user session
      parameters: []
      responses:
        "200":
          description: log in
        "401":
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
  "/logout":
    delete:
      summary: " delete session"
      tags:
        - Logout
      responses:
        "200":
          description: log out
        "401":
          description: authentication failed
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
